import org.testng.annotations.*;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library --with testng'
 * by 'Karanjit_Singh' at '8/2/17 11:55 AM' with Gradle 3.1
 *
 * @author Karanjit_Singh, @date 8/2/17 11:55 AM
 *
 *
 *
 */

public class HelloWorldTest {
    @Test public void appHasAGreeting() {
        HelloWorldApp classUnderTest = new HelloWorldApp();
        assertEquals(classUnderTest.getGreeting(), "Hello World!", "app should have a greeting");
    }
}
